# Generated by Django 3.0.5 on 2020-04-30 17:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consult', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('business_name', models.CharField(default='Não Obrigatório', max_length=256)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=555)),
                ('state', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('my_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Calendar')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='users.Users')),
                ('consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult.Consultancies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.Users')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales History',
            },
        ),
        migrations.CreateModel(
            name='RateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_date', models.DateField(default=django.utils.timezone.now)),
                ('consult_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult.Consultancies')),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_by', to='users.Users')),
                ('given_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_to', to='users.Users')),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
            },
        ),
        migrations.CreateModel(
            name='PurchasesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult.Consultancies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases History',
            },
        ),
        migrations.AddField(
            model_name='calendar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users'),
        ),
    ]
